import type { PlaybookDefinition, PlaybookTask } from '@/domain/playbook';

/**
 * The playbooks Jarvis ships with.
 *
 * Each is a *shape*, not a script: a set of roles, an order, the checks that must run and the
 * reviews that must happen. What none of them is, is a way to gain capability — every task names
 * a role, every role's ceiling is fixed in `agent-role.ts`, and `validatePlaybook` rejects any
 * definition that asks for more than its role already allows. A playbook can add a check; there
 * is no field in the schema that removes one.
 *
 * They are seeded on boot and re-seeded idempotently: an unchanged definition produces no new
 * version, so restarting Jarvis does not grow the history.
 */

/** Every graph that changes files ends the same way, so this is written once. */
function deliveryTail(dependsOn: readonly string[], reviewKeys: readonly string[]): PlaybookTask[] {
  return [
    {
      key: 'tv',
      title: "Run the repository's own checks",
      description:
        'Run the checks this repository defines against the integrated result and record what really happened. A check that cannot run here is recorded as unavailable — never as a pass.',
      role: 'verifier',
      taskType: 'verification',
      dependsOn: [...dependsOn],
      workspaceRequirement: 'integration',
      requiresRepository: true,
      expectedFileAreas: [],
      declaredWriteSet: [],
      acceptanceCriteria: ['Every required check ran or is honestly marked unavailable'],
      expectedInputs: ['The integrated branch'],
      expectedOutputs: ['A verification record per check'],
      maxAttempts: 1,
      repairRound: 0,
      estimatedCost: 'small',
      condition: 'always',
    },
    {
      key: 'tr',
      title: 'Independent review',
      description:
        'A fresh session reviews the finished diff against the approved plan, the acceptance criteria and the verification evidence. It has not seen how the work was written, and it cannot edit, commit or approve anything.',
      role: 'reviewer',
      taskType: 'review',
      dependsOn: ['tv'],
      workspaceRequirement: 'readonly_clone',
      requiresRepository: true,
      expectedFileAreas: [],
      declaredWriteSet: [],
      acceptanceCriteria: [
        'Every blocking finding quotes real evidence',
        'No approval while a required check failed',
      ],
      expectedInputs: ['The integrated diff', 'Verification results'],
      expectedOutputs: ['A verdict and structured findings'],
      maxAttempts: 1,
      repairRound: 0,
      estimatedCost: 'medium',
      condition: 'always',
    },
    {
      key: 'td',
      title: 'Open the draft pull request',
      description:
        'Push the mission integration branch and open a draft pull request, then write the completion receipt. Deterministic; nothing is merged and the pull request is a draft in every case.',
      role: 'integrator',
      taskType: 'delivery',
      dependsOn: ['tr', ...reviewKeys],
      workspaceRequirement: 'integration',
      requiresRepository: true,
      expectedFileAreas: [],
      declaredWriteSet: [],
      acceptanceCriteria: ['The pull request is a draft', 'The default branch is untouched'],
      expectedInputs: ['An approved review'],
      expectedOutputs: ['A draft pull request', 'A completion receipt'],
      maxAttempts: 1,
      repairRound: 0,
      estimatedCost: 'small',
      condition: 'always',
    },
  ];
}

const integrationTask = (dependsOn: readonly string[]): PlaybookTask => ({
  key: 'ti',
  title: 'Merge the finished work onto the mission branch',
  description:
    'Deterministic git: merge each finished task branch into the mission integration branch in dependency order. A conflict stops here with both sides intact; nothing is discarded to make a merge succeed.',
  role: 'integrator',
  taskType: 'integration',
  dependsOn: [...dependsOn],
  workspaceRequirement: 'integration',
  requiresRepository: true,
  expectedFileAreas: [],
  declaredWriteSet: [],
  acceptanceCriteria: ['Every task branch merged without discarding either side'],
  expectedInputs: ['Every finished task branch'],
  expectedOutputs: ['A mission integration branch'],
  maxAttempts: 1,
  repairRound: 0,
  estimatedCost: 'small',
  condition: 'always',
});

/* ------------------------------------------------------------ software feature */

const SOFTWARE_FEATURE: PlaybookDefinition = {
  key: 'software_feature',
  name: 'Software feature',
  description:
    'Inspect, plan, optionally research, implement with tests, integrate, verify, review independently, repair once if needed, and open a draft pull request.',
  supportedProjectTypes: ['software'],
  riskLevel: 'moderate',
  inputs: [
    {
      key: 'feature',
      label: 'What should exist afterwards?',
      kind: 'long_text',
      required: true,
      help: 'Describe the outcome, not the implementation.',
      choices: [],
      default: null,
    },
  ],
  tasks: [
    {
      key: 'tq',
      title: 'Investigate what already exists',
      description:
        'Read the repository and report how {{feature}} would fit what is already there. Change nothing. Say where the existing conventions are, what would have to move, and what you are unsure about.',
      role: 'researcher',
      taskType: 'investigation',
      dependsOn: [],
      workspaceRequirement: 'readonly_clone',
      requiresRepository: true,
      expectedFileAreas: [],
      declaredWriteSet: [],
      acceptanceCriteria: ['Findings are sourced to files and lines'],
      expectedInputs: [],
      expectedOutputs: ['A sourced findings artifact'],
      maxAttempts: 1,
      repairRound: 0,
      estimatedCost: 'small',
      condition: 'if_repository',
    },
    {
      key: 'tb',
      title: 'Implement {{feature}}',
      description:
        'Implement the approved plan, with the tests the change deserves. Stay inside the plan: if the right thing to do turns out to be outside it, stop and say so rather than doing it.',
      role: 'builder',
      taskType: 'implementation',
      dependsOn: ['tq'],
      workspaceRequirement: 'task_workspace',
      requiresRepository: true,
      expectedFileAreas: [],
      declaredWriteSet: ['.'],
      acceptanceCriteria: ['The feature works', 'Tests cover the new behaviour'],
      expectedInputs: ['The investigation'],
      expectedOutputs: ['A task branch'],
      maxAttempts: 1,
      repairRound: 0,
      estimatedCost: 'large',
      condition: 'always',
    },
    integrationTask(['tb']),
    ...deliveryTail(['ti'], []),
  ],
  additionalChecks: [],
  requiredReviews: [],
  ownerApprovalPoints: [
    'The plan',
    'The task graph',
    'The draft pull request (you merge it, not Jarvis)',
  ],
  maxParallelTasks: 2,
  maxRepairRounds: 2,
  expectedArtifacts: ['An investigation report', 'A completion receipt'],
  completionDefinition:
    'A draft pull request exists, its checks ran, an independent reviewer approved it, and a completion receipt says what is and is not true about it.',
  canDispatchExternalBuild: false,
};

/* --------------------------------------------------- bug investigation and repair */

const BUG_FIX: PlaybookDefinition = {
  key: 'bug_investigation',
  name: 'Bug investigation and repair',
  description:
    'Generate competing hypotheses, investigate each independently, choose the one the evidence supports, then fix it with a regression test.',
  supportedProjectTypes: ['software'],
  riskLevel: 'moderate',
  inputs: [
    {
      key: 'symptom',
      label: 'What goes wrong?',
      kind: 'long_text',
      required: true,
      help: 'What you saw, what you expected, and how to reproduce it if you know.',
      choices: [],
      default: null,
    },
  ],
  tasks: [
    {
      key: 'th1',
      title: 'Hypothesis A: where the fault could be',
      description:
        'Symptom: {{symptom}}\n\nForm one hypothesis about the cause and try to prove or disprove it from the code and history. Report the evidence either way. A disproved hypothesis is a useful result — do not stretch to make it fit.',
      role: 'researcher',
      taskType: 'investigation',
      dependsOn: [],
      workspaceRequirement: 'readonly_clone',
      requiresRepository: true,
      expectedFileAreas: [],
      declaredWriteSet: [],
      acceptanceCriteria: [
        'The hypothesis is stated before the evidence',
        'Evidence cites files and lines',
      ],
      expectedInputs: [],
      expectedOutputs: ['A sourced hypothesis report'],
      maxAttempts: 1,
      repairRound: 0,
      estimatedCost: 'small',
      condition: 'always',
    },
    {
      key: 'th2',
      title: 'Hypothesis B: a different explanation',
      description:
        'Symptom: {{symptom}}\n\nForm a hypothesis that is genuinely different from the obvious one, and test it the same way. Two agents arriving at the same answer independently is worth something; two agents told the same story is not.',
      role: 'researcher',
      taskType: 'investigation',
      dependsOn: [],
      workspaceRequirement: 'readonly_clone',
      requiresRepository: true,
      expectedFileAreas: [],
      declaredWriteSet: [],
      acceptanceCriteria: ['The hypothesis differs materially from A'],
      expectedInputs: [],
      expectedOutputs: ['A sourced hypothesis report'],
      maxAttempts: 1,
      repairRound: 0,
      estimatedCost: 'small',
      condition: 'always',
    },
    {
      key: 'ts',
      title: 'Choose the cause the evidence supports',
      description:
        'Compare the hypotheses. Say which is better supported and why, quoting the evidence. If neither is supported, say that — a root cause is not established because an agent suggested it, and "we do not know yet" is a legitimate outcome that stops here and asks.',
      role: 'researcher',
      taskType: 'synthesis',
      dependsOn: ['th1', 'th2'],
      workspaceRequirement: 'none',
      requiresRepository: false,
      expectedFileAreas: [],
      declaredWriteSet: [],
      acceptanceCriteria: [
        'The chosen cause is supported by quoted evidence',
        'Disagreement is preserved',
      ],
      expectedInputs: ['Both hypothesis reports'],
      expectedOutputs: ['A decision with its evidence'],
      maxAttempts: 1,
      repairRound: 0,
      estimatedCost: 'small',
      condition: 'always',
    },
    {
      key: 'tb',
      title: 'Fix the cause and add a regression test',
      description:
        'Fix the cause the evidence supports. Add a test that fails without the fix and passes with it — a fix without that test is not finished. Do not fix anything else along the way.',
      role: 'builder',
      taskType: 'implementation',
      dependsOn: ['ts'],
      workspaceRequirement: 'task_workspace',
      requiresRepository: true,
      expectedFileAreas: [],
      declaredWriteSet: ['.'],
      acceptanceCriteria: ['A regression test fails without the fix', 'Nothing unrelated changed'],
      expectedInputs: ['The chosen cause'],
      expectedOutputs: ['A task branch with the fix and its test'],
      maxAttempts: 1,
      repairRound: 0,
      estimatedCost: 'medium',
      condition: 'always',
    },
    integrationTask(['tb']),
    ...deliveryTail(['ti'], []),
  ],
  additionalChecks: [],
  requiredReviews: [],
  ownerApprovalPoints: [
    'The plan',
    'The task graph',
    'The chosen root cause if the evidence is thin',
  ],
  maxParallelTasks: 2,
  maxRepairRounds: 2,
  expectedArtifacts: ['Two hypothesis reports', 'A decision with evidence', 'A completion receipt'],
  completionDefinition:
    'The cause is identified with evidence, fixed, covered by a regression test, reviewed, and delivered as a draft pull request.',
  canDispatchExternalBuild: false,
};

/* --------------------------------------------------------------- repository audit */

const REPOSITORY_AUDIT: PlaybookDefinition = {
  key: 'repository_audit',
  name: 'Repository audit',
  description:
    'A read-only survey of architecture, reliability, security, test coverage and CI health, with prioritised recommendations and evidence for each.',
  supportedProjectTypes: ['software'],
  riskLevel: 'read_only',
  inputs: [],
  tasks: [
    {
      key: 't1',
      title: 'Architecture and reliability',
      description:
        'Survey how this repository is put together and where it is fragile. Report what you observed with file references, separately from what you infer. Do not change anything.',
      role: 'researcher',
      taskType: 'research',
      dependsOn: [],
      workspaceRequirement: 'readonly_clone',
      requiresRepository: true,
      expectedFileAreas: [],
      declaredWriteSet: [],
      acceptanceCriteria: ['Every finding cites a file'],
      expectedInputs: [],
      expectedOutputs: ['Architecture findings'],
      maxAttempts: 1,
      repairRound: 0,
      estimatedCost: 'medium',
      condition: 'always',
    },
    {
      key: 't2',
      title: 'Security and data handling',
      description:
        'Look specifically at authentication, authorisation, credential handling, data boundaries and anything that leaves the process. Report what is there, not what should be — and quote it.',
      role: 'security_reviewer',
      taskType: 'security_review',
      dependsOn: [],
      workspaceRequirement: 'readonly_clone',
      requiresRepository: true,
      expectedFileAreas: [],
      declaredWriteSet: [],
      acceptanceCriteria: ['Findings are specific and quoted'],
      expectedInputs: [],
      expectedOutputs: ['Security findings'],
      maxAttempts: 1,
      repairRound: 0,
      estimatedCost: 'medium',
      condition: 'always',
    },
    {
      key: 't3',
      title: 'Tests and build health',
      description:
        'Where is the test coverage thin, and what does CI actually run? Report gaps with evidence: a missing test is a specific missing test, not a general observation that coverage could be better.',
      role: 'researcher',
      taskType: 'research',
      dependsOn: [],
      workspaceRequirement: 'readonly_clone',
      requiresRepository: true,
      expectedFileAreas: [],
      declaredWriteSet: [],
      acceptanceCriteria: ['Gaps are specific'],
      expectedInputs: [],
      expectedOutputs: ['Test and CI findings'],
      maxAttempts: 1,
      repairRound: 0,
      estimatedCost: 'medium',
      condition: 'always',
    },
    {
      key: 't4',
      title: 'Prioritise what is worth doing',
      description:
        'Combine the three surveys into one prioritised list. Each recommendation names what to do, why, and the evidence behind it. Where the surveys disagree, keep the disagreement. Each item should be small enough to become its own mission.',
      role: 'researcher',
      taskType: 'synthesis',
      dependsOn: ['t1', 't2', 't3'],
      workspaceRequirement: 'none',
      requiresRepository: false,
      expectedFileAreas: [],
      declaredWriteSet: [],
      acceptanceCriteria: [
        'Every recommendation links to its evidence',
        'Each item could become one mission',
      ],
      expectedInputs: ['All three surveys'],
      expectedOutputs: ['A prioritised audit report'],
      maxAttempts: 1,
      repairRound: 0,
      estimatedCost: 'small',
      condition: 'always',
    },
  ],
  additionalChecks: [],
  requiredReviews: [],
  ownerApprovalPoints: ['The task graph', 'Which findings become their own missions'],
  maxParallelTasks: 3,
  maxRepairRounds: 0,
  expectedArtifacts: ['A prioritised audit report'],
  completionDefinition:
    'A prioritised, evidenced audit report exists. Nothing in the repository changed.',
  canDispatchExternalBuild: false,
};

/* --------------------------------------------------------------- research report */

const RESEARCH_REPORT: PlaybookDefinition = {
  key: 'research_report',
  name: 'Research report',
  description:
    'Several focused research strands on one question, graded sources, and a synthesis that preserves disagreement rather than manufacturing consensus.',
  supportedProjectTypes: [],
  riskLevel: 'read_only',
  inputs: [
    {
      key: 'question',
      label: 'What do you want to know?',
      kind: 'long_text',
      required: true,
      help: 'One question. A report that answers three questions badly is worse than one that answers one well.',
      choices: [],
      default: null,
    },
  ],
  tasks: [
    {
      key: 't1',
      title: 'Research strand 1',
      description:
        'Question: {{question}}\n\nAnswer it from what exists in this project. Cite everything. Grade each source: something you read in the code is stronger evidence than something you inferred from a name.',
      role: 'researcher',
      taskType: 'research',
      dependsOn: [],
      workspaceRequirement: 'readonly_clone',
      requiresRepository: true,
      expectedFileAreas: [],
      declaredWriteSet: [],
      acceptanceCriteria: ['Sources are cited and graded'],
      expectedInputs: [],
      expectedOutputs: ['Findings'],
      maxAttempts: 1,
      repairRound: 0,
      estimatedCost: 'medium',
      condition: 'if_repository',
    },
    {
      key: 't2',
      title: 'Research strand 2 (web)',
      description:
        'Question: {{question}}\n\nAnswer it from outside sources. Cite URLs. Say where sources disagree with each other rather than picking the one you like.',
      role: 'researcher',
      permissionProfileId: 'readonly_repo_web',
      taskType: 'research',
      dependsOn: [],
      workspaceRequirement: 'none',
      requiresRepository: false,
      expectedFileAreas: [],
      declaredWriteSet: [],
      acceptanceCriteria: ['Every claim has a URL'],
      expectedInputs: [],
      expectedOutputs: ['Findings'],
      maxAttempts: 1,
      repairRound: 0,
      estimatedCost: 'medium',
      condition: 'if_web_research_allowed',
    },
    {
      key: 't3',
      title: 'Synthesise',
      description:
        'Write the report. Where the strands agree, say so once. Where they disagree, present both with their evidence and say which is better supported — do not average them into a consensus that neither strand actually holds.',
      role: 'researcher',
      permissionProfileId: 'artifact_only',
      taskType: 'synthesis',
      dependsOn: ['t1', 't2'],
      workspaceRequirement: 'none',
      requiresRepository: false,
      expectedFileAreas: [],
      declaredWriteSet: [],
      acceptanceCriteria: ['Disagreements survive', 'Facts and inference are distinguishable'],
      expectedInputs: ['Every strand'],
      expectedOutputs: ['A sourced report'],
      maxAttempts: 1,
      repairRound: 0,
      estimatedCost: 'small',
      condition: 'always',
    },
  ],
  additionalChecks: [],
  requiredReviews: [],
  ownerApprovalPoints: ['The task graph', 'Any next actions the report proposes'],
  maxParallelTasks: 3,
  maxRepairRounds: 0,
  expectedArtifacts: ['A sourced research report'],
  completionDefinition: 'A sourced report exists and nothing was changed anywhere.',
  canDispatchExternalBuild: false,
};

/* --------------------------------------------------------------- website feature */

const WEBSITE_FEATURE: PlaybookDefinition = {
  key: 'website_feature',
  name: 'Website feature',
  description:
    'A web change with a production build, responsive and accessibility review, and browser smoke checks. Never deploys production.',
  supportedProjectTypes: ['software', 'website'],
  riskLevel: 'moderate',
  inputs: [
    {
      key: 'feature',
      label: 'What should the site do?',
      kind: 'long_text',
      required: true,
      choices: [],
      default: null,
      help: null,
    },
  ],
  tasks: [
    {
      key: 'tb',
      title: 'Build {{feature}}',
      description:
        'Implement the approved plan. Layout must work at a phone width as well as a desktop one, and every control must be reachable by keyboard. Add or update the tests the change deserves.',
      role: 'builder',
      taskType: 'implementation',
      dependsOn: [],
      workspaceRequirement: 'task_workspace',
      requiresRepository: true,
      expectedFileAreas: [],
      declaredWriteSet: ['.'],
      acceptanceCriteria: [
        'The page does not scroll sideways at 375px',
        'Every control is keyboard reachable',
      ],
      expectedInputs: [],
      expectedOutputs: ['A task branch'],
      maxAttempts: 1,
      repairRound: 0,
      estimatedCost: 'large',
      condition: 'always',
    },
    integrationTask(['tb']),
    ...deliveryTail(['ti'], ['tux']),
    {
      key: 'tux',
      title: 'UI and accessibility review',
      description:
        'Review what a person actually sees and can do: layout at small widths, contrast, focus order, screen-reader labels, and whether the empty and failure states say something useful. Read-only.',
      role: 'ux_reviewer',
      taskType: 'ux_review',
      dependsOn: ['tv'],
      workspaceRequirement: 'readonly_clone',
      requiresRepository: true,
      expectedFileAreas: [],
      declaredWriteSet: [],
      acceptanceCriteria: ['Findings name a component and a viewport'],
      expectedInputs: ['The integrated diff'],
      expectedOutputs: ['A verdict and findings'],
      maxAttempts: 1,
      repairRound: 0,
      estimatedCost: 'medium',
      condition: 'always',
    },
  ],
  additionalChecks: [
    { id: 'build', label: 'Production build', required: true, blocksDelivery: true },
    { id: 'a11y', label: 'Accessibility checks', required: false, blocksDelivery: false },
  ],
  requiredReviews: ['ux_reviewer'],
  ownerApprovalPoints: ['The plan', 'The task graph', 'The draft pull request'],
  maxParallelTasks: 2,
  maxRepairRounds: 2,
  expectedArtifacts: ['A completion receipt'],
  completionDefinition:
    'A draft pull request exists with a passing production build and an independent UI review. Nothing was deployed.',
  canDispatchExternalBuild: false,
};

/* -------------------------------------------------------------------- iOS feature */

const IOS_FEATURE: PlaybookDefinition = {
  key: 'ios_feature',
  name: 'iOS feature',
  description:
    'An iOS change aware of entitlements, App Groups, widgets, StoreKit and the privacy manifest. Where the worker is not a Mac, the Xcode build is honestly reported as unavailable and left to CI.',
  supportedProjectTypes: ['software', 'ios_app'],
  riskLevel: 'moderate',
  inputs: [
    {
      key: 'feature',
      label: 'What should the app do?',
      kind: 'long_text',
      required: true,
      choices: [],
      default: null,
      help: null,
    },
  ],
  tasks: [
    {
      key: 'tq',
      title: 'Check the iOS surfaces this touches',
      description:
        'Before anything is written: does {{feature}} affect entitlements, the bundle identifier, an App Group, a widget extension, StoreKit products, notification permissions or the privacy manifest? Report what it touches with evidence from the project files. Change nothing.',
      role: 'ios_specialist',
      taskType: 'investigation',
      dependsOn: [],
      workspaceRequirement: 'readonly_clone',
      requiresRepository: true,
      expectedFileAreas: [],
      declaredWriteSet: [],
      acceptanceCriteria: ['Every affected surface is named or explicitly ruled out'],
      expectedInputs: [],
      expectedOutputs: ['An iOS impact report'],
      maxAttempts: 1,
      repairRound: 0,
      estimatedCost: 'small',
      condition: 'always',
    },
    {
      key: 'tb',
      title: 'Implement {{feature}}',
      description:
        'Implement the approved plan, honouring the impact report. Support Dynamic Type and VoiceOver. Do not change the bundle identifier, the team, entitlements or signing configuration — those are the owner’s to change, not yours.',
      role: 'builder',
      taskType: 'implementation',
      dependsOn: ['tq'],
      workspaceRequirement: 'task_workspace',
      requiresRepository: true,
      expectedFileAreas: [],
      declaredWriteSet: ['.'],
      acceptanceCriteria: [
        'Signing and entitlements are unchanged',
        'The feature supports Dynamic Type and VoiceOver',
      ],
      expectedInputs: ['The impact report'],
      expectedOutputs: ['A task branch'],
      maxAttempts: 1,
      repairRound: 0,
      estimatedCost: 'large',
      condition: 'always',
    },
    integrationTask(['tb']),
    ...deliveryTail(['ti'], []),
  ],
  additionalChecks: [
    { id: 'swift_lint', label: 'Swift lint or format', required: false, blocksDelivery: false },
    { id: 'xcode_build', label: 'Xcode build', required: true, blocksDelivery: true },
    { id: 'simulator_tests', label: 'Simulator tests', required: false, blocksDelivery: false },
  ],
  requiredReviews: [],
  ownerApprovalPoints: ['The plan', 'The task graph', 'The draft pull request'],
  maxParallelTasks: 2,
  maxRepairRounds: 2,
  expectedArtifacts: ['An iOS impact report', 'A completion receipt'],
  completionDefinition:
    'A draft pull request exists. Where the worker is not a Mac, the Xcode build is marked unavailable here and left to the repository’s own macOS CI — that is not a pass.',
  canDispatchExternalBuild: false,
};

/* ------------------------------------------------------------------- TestFlight */

const TESTFLIGHT: PlaybookDefinition = {
  key: 'testflight_build',
  name: 'TestFlight build',
  description:
    'Verify a reviewed commit is releasable, then ask you to approve a TestFlight build for that exact commit. Apple credentials stay in the repository’s own Actions secrets and never enter an agent session.',
  supportedProjectTypes: ['software', 'ios_app'],
  riskLevel: 'high',
  inputs: [],
  tasks: [
    {
      key: 'tv',
      title: "Run the repository's own checks",
      description:
        'Run what the repository defines. A build that has not been checked is not a build anyone should ship to testers.',
      role: 'verifier',
      taskType: 'verification',
      dependsOn: [],
      workspaceRequirement: 'integration',
      requiresRepository: true,
      expectedFileAreas: [],
      declaredWriteSet: [],
      acceptanceCriteria: ['Every required check ran or is honestly marked unavailable'],
      expectedInputs: [],
      expectedOutputs: ['Verification records'],
      maxAttempts: 1,
      repairRound: 0,
      estimatedCost: 'small',
      condition: 'always',
    },
    {
      key: 'trv',
      title: 'Release verification',
      description:
        'Check that what would be built is genuinely releasable: the version and build number make sense, the configured workflow exists, and the repository declares the secrets that workflow needs. Check that they are *declared* — you have no capability to read one, and you must not try.',
      role: 'release_verifier',
      taskType: 'release_verification',
      dependsOn: ['tv'],
      workspaceRequirement: 'readonly_clone',
      requiresRepository: true,
      expectedFileAreas: [],
      declaredWriteSet: [],
      acceptanceCriteria: [
        'The workflow file exists',
        'Required secret names are declared',
        'No secret value was read',
      ],
      expectedInputs: ['Verification results'],
      expectedOutputs: ['A release readiness verdict'],
      maxAttempts: 1,
      repairRound: 0,
      estimatedCost: 'small',
      condition: 'always',
    },
    {
      key: 'tci',
      title: 'Ask you to approve the build',
      description:
        'Put the exact repository, workflow, branch and commit in front of the owner. Jarvis dispatches nothing until they approve *that commit*; if the code moves afterwards, the approval stops applying and has to be given again.',
      role: 'release_verifier',
      taskType: 'ci_dispatch',
      dependsOn: ['trv'],
      workspaceRequirement: 'none',
      requiresRepository: false,
      expectedFileAreas: [],
      declaredWriteSet: [],
      acceptanceCriteria: ['The owner approved this exact commit'],
      expectedInputs: ['The release readiness verdict'],
      expectedOutputs: ['A dispatch record'],
      maxAttempts: 1,
      repairRound: 0,
      estimatedCost: 'small',
      condition: 'always',
    },
  ],
  additionalChecks: [
    { id: 'xcode_build', label: 'Xcode build', required: true, blocksDelivery: true },
  ],
  requiredReviews: ['release_verifier'],
  ownerApprovalPoints: ['The task graph', 'The TestFlight dispatch, bound to one exact commit'],
  maxParallelTasks: 1,
  maxRepairRounds: 0,
  expectedArtifacts: ['A release readiness verdict', 'A dispatch record'],
  completionDefinition:
    'A workflow you approved was dispatched for an exact commit, and its archive, export and upload stages are reported separately. Apple’s own processing is reported as pending because Jarvis cannot see it.',
  canDispatchExternalBuild: true,
};

/* ---------------------------------------------------------- new project starter */

const NEW_PROJECT: PlaybookDefinition = {
  key: 'new_project_starter',
  name: 'New project from a template',
  description:
    'Generate a new project from an approved private template, with its identity confirmed explicitly. Jarvis never creates a public repository and never copies another app’s credentials into a generated file.',
  supportedProjectTypes: ['software', 'ios_app', 'website'],
  riskLevel: 'moderate',
  inputs: [
    {
      key: 'app_name',
      label: 'App name',
      kind: 'text',
      required: true,
      choices: [],
      default: null,
      help: null,
    },
    {
      key: 'bundle_id',
      label: 'Bundle identifier',
      kind: 'text',
      required: true,
      choices: [],
      default: null,
      help: 'Reverse-DNS, e.g. com.example.app.',
    },
    {
      key: 'template',
      label: 'Template repository',
      kind: 'repository',
      required: true,
      choices: [],
      default: null,
      help: 'A private template you already trust. Jarvis will not invent one.',
    },
    {
      key: 'visibility',
      label: 'Repository visibility',
      kind: 'choice',
      required: true,
      choices: ['private'],
      default: 'private',
      help: 'Private. Jarvis has no option to create a public repository.',
    },
  ],
  tasks: [
    {
      key: 'tq',
      title: 'Confirm the project identity',
      description:
        'Show back exactly what will be created: {{app_name}}, {{bundle_id}}, from {{template}}, visibility {{visibility}}. Report anything in the template that would need changing — and anything that looks like it carries another app’s configuration, because that must never be copied forward.',
      role: 'researcher',
      taskType: 'investigation',
      dependsOn: [],
      workspaceRequirement: 'readonly_clone',
      requiresRepository: true,
      expectedFileAreas: [],
      declaredWriteSet: [],
      acceptanceCriteria: [
        'Identity is echoed back in full',
        'Anything carrying another app’s configuration is flagged',
      ],
      expectedInputs: [],
      expectedOutputs: ['An identity confirmation'],
      maxAttempts: 1,
      repairRound: 0,
      estimatedCost: 'small',
      condition: 'always',
    },
    {
      key: 'tb',
      title: 'Generate the project',
      description:
        'Produce the project from the template with the confirmed identity. Never copy a credential, a certificate, a provisioning profile or a repository secret into a generated file — if the template contains one, that is a finding, not something to carry forward.',
      role: 'builder',
      taskType: 'implementation',
      dependsOn: ['tq'],
      workspaceRequirement: 'task_workspace',
      requiresRepository: true,
      expectedFileAreas: [],
      declaredWriteSet: ['.'],
      acceptanceCriteria: [
        'The identity matches what was confirmed',
        'No credential from any other app appears anywhere',
      ],
      expectedInputs: ['The identity confirmation'],
      expectedOutputs: ['A task branch containing the new project'],
      maxAttempts: 1,
      repairRound: 0,
      estimatedCost: 'large',
      condition: 'always',
    },
    integrationTask(['tb']),
    ...deliveryTail(['ti'], ['tsec']),
    {
      key: 'tsec',
      title: 'Check nothing secret came along',
      description:
        'Read the generated project specifically for credentials, keys, tokens or another app’s configuration that should not be there. This is why the starter has a security review that a feature branch does not.',
      role: 'security_reviewer',
      taskType: 'security_review',
      dependsOn: ['tv'],
      workspaceRequirement: 'readonly_clone',
      requiresRepository: true,
      expectedFileAreas: [],
      declaredWriteSet: [],
      acceptanceCriteria: ['No credential material is present'],
      expectedInputs: ['The generated project'],
      expectedOutputs: ['A verdict and findings'],
      maxAttempts: 1,
      repairRound: 0,
      estimatedCost: 'small',
      condition: 'always',
    },
  ],
  additionalChecks: [],
  requiredReviews: ['security_reviewer'],
  ownerApprovalPoints: [
    'The project identity, in full',
    'The task graph',
    'Creating the repository itself, which you do — Jarvis has no capability to create one',
  ],
  maxParallelTasks: 1,
  maxRepairRounds: 1,
  expectedArtifacts: ['An identity confirmation', 'A completion receipt'],
  completionDefinition:
    'A draft pull request contains the generated project, reviewed for stray credentials. Creating the repository is a step you take; Jarvis tells you exactly what to run.',
  canDispatchExternalBuild: false,
};

/* --------------------------------------------------------------- report artifact */

const REPORT_ARTIFACT: PlaybookDefinition = {
  key: 'report_artifact',
  name: 'Structured report',
  description:
    'A durable Markdown report or outline built from Jarvis’s own evidence. Deliberately not a PowerPoint or a PDF: Jarvis has no way to verify one of those looks right, and would rather produce something true than something that renders.',
  supportedProjectTypes: [],
  riskLevel: 'read_only',
  inputs: [
    {
      key: 'topic',
      label: 'What should the report cover?',
      kind: 'long_text',
      required: true,
      choices: [],
      default: null,
      help: null,
    },
  ],
  tasks: [
    {
      key: 't1',
      title: 'Gather the material',
      description:
        'Collect what is actually known about {{topic}} from this project’s evidence. Cite each item. Where the evidence is thin, say so — the report will say so too.',
      role: 'researcher',
      taskType: 'research',
      dependsOn: [],
      workspaceRequirement: 'readonly_clone',
      requiresRepository: true,
      expectedFileAreas: [],
      declaredWriteSet: [],
      acceptanceCriteria: ['Everything is cited'],
      expectedInputs: [],
      expectedOutputs: ['Source material'],
      maxAttempts: 1,
      repairRound: 0,
      estimatedCost: 'medium',
      condition: 'if_repository',
    },
    {
      key: 't2',
      title: 'Write the report',
      description:
        'Write a structured Markdown report on {{topic}}. Lead with what is true and evidenced; mark anything inferred as inferred. Do not pad it to look thorough.',
      role: 'researcher',
      permissionProfileId: 'artifact_only',
      taskType: 'report',
      dependsOn: ['t1'],
      workspaceRequirement: 'none',
      requiresRepository: false,
      expectedFileAreas: [],
      declaredWriteSet: [],
      acceptanceCriteria: ['Evidence and inference are distinguishable'],
      expectedInputs: ['The source material'],
      expectedOutputs: ['A Markdown report artifact'],
      maxAttempts: 1,
      repairRound: 0,
      estimatedCost: 'small',
      condition: 'always',
    },
  ],
  additionalChecks: [],
  requiredReviews: [],
  ownerApprovalPoints: ['The task graph'],
  maxParallelTasks: 2,
  maxRepairRounds: 0,
  expectedArtifacts: ['A Markdown report'],
  completionDefinition: 'A structured, sourced Markdown report exists as a mission artifact.',
  canDispatchExternalBuild: false,
};

export const BUILT_IN_PLAYBOOKS: readonly PlaybookDefinition[] = [
  SOFTWARE_FEATURE,
  BUG_FIX,
  REPOSITORY_AUDIT,
  RESEARCH_REPORT,
  WEBSITE_FEATURE,
  IOS_FEATURE,
  TESTFLIGHT,
  NEW_PROJECT,
  REPORT_ARTIFACT,
];
