import { readFile, readdir } from 'node:fs/promises';
import path from 'node:path';
import { sql } from 'drizzle-orm';
import type { Database } from './client';

/**
 * Migration runner.
 *
 * The SQL in `drizzle/` is generated by drizzle-kit and applied here with a tiny, driver-agnostic
 * runner so that Neon, node-postgres and PGlite all follow exactly the same path — the local and
 * test databases are therefore schema-identical to production by construction.
 *
 * Applied migrations are recorded in `_jarvis_migrations`, making the runner idempotent and safe
 * to invoke on every deploy.
 */

const MIGRATIONS_TABLE = '_jarvis_migrations';

export interface MigrationResult {
  readonly applied: readonly string[];
  readonly skipped: readonly string[];
}

export function splitStatements(sqlText: string): string[] {
  return sqlText
    .split('--> statement-breakpoint')
    .map((statement) => statement.trim())
    .filter((statement) => statement.length > 0 && !/^(--[^\n]*\n?)*$/.test(statement));
}

export async function runMigrations(
  db: Database,
  migrationsDir = path.join(process.cwd(), 'drizzle'),
): Promise<MigrationResult> {
  await db.execute(
    sql.raw(
      `CREATE TABLE IF NOT EXISTS "${MIGRATIONS_TABLE}" (
         "name" text PRIMARY KEY,
         "applied_at" timestamp with time zone NOT NULL DEFAULT now()
       )`,
    ),
  );

  const existing = await db.execute(sql.raw(`SELECT "name" FROM "${MIGRATIONS_TABLE}"`));
  const rows = extractRows(existing);
  const already = new Set(rows.map((row) => String(row.name)));

  const entries = (await readdir(migrationsDir)).filter((file) => file.endsWith('.sql')).sort();

  const applied: string[] = [];
  const skipped: string[] = [];

  for (const file of entries) {
    if (already.has(file)) {
      skipped.push(file);
      continue;
    }
    const contents = await readFile(path.join(migrationsDir, file), 'utf8');
    for (const statement of splitStatements(contents)) {
      await db.execute(sql.raw(statement));
    }
    await db.execute(
      sql`INSERT INTO ${sql.identifier(MIGRATIONS_TABLE)} ("name") VALUES (${file}) ON CONFLICT DO NOTHING`,
    );
    applied.push(file);
  }

  return { applied, skipped };
}

/** Normalise the shape differences between the drivers' `execute` return values. */
function extractRows(result: unknown): Array<Record<string, unknown>> {
  if (Array.isArray(result)) return result as Array<Record<string, unknown>>;
  if (result && typeof result === 'object' && 'rows' in result) {
    const rows = (result as { rows: unknown }).rows;
    if (Array.isArray(rows)) return rows as Array<Record<string, unknown>>;
  }
  return [];
}
